#.travis.yml

language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build --prod
  # - export CHROME_BIN=chromium-browser
  # - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  # - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

notifications:
  email:
    on_failure: change
    on_success: change
